module.exports = {
  movie: [
    "<div class='row'>",
      "<div class='col-md-2'></div>",
      "<div class='col-md-8'>",
          "<div class='thumbnail'>",
            "<img src='<%=photo %>'>",
          "</div>",
              "<div class='col-md-2 rating'>",
                "<span class='glyphicon glyphicon-star-empty' style='color: gold;' aria-hidden='true'><%=rating %></span>",
                "<span class='glyphicon glyphicon-star-empty' style='color: gold;' aria-hidden='true'></span>",
              "</div>",
              "<div class='col-md-8 title'>",
                "<h3><%=title %></h3>",
              "</div>",
              "<div class='col-md-2 release'>",
                "<h3><%=release %></h3>",
              "</div>",
          "<div class='col-md-12 review'>",
              "<p><%=plot %></p>",
          "</div>",
          "<div class='col-md-12 buttons'>",
              "<p>",
                "<a href='#'' class='btn btn-primary remove' role='button'>Remove From List</a>",
              "</p>",
          "</div>",
        "</div>",
        "<div class='col-md-2'></div>",
      "</div>"

  ].join(""),
  form: [
    "<form>",
      "<form class='form-inline'>",
        "<div class='form-group'>",
          "<input type='text' class='form-control' id='title' name='title' placeholder='Title'>",
        "</div>",
        "<div class='form-group'>",
          "<input type='text' class='form-control' id='photo' name='photo' placeholder='http://something.com'>",
        "</div>",
        "<div class='form-group'>",
          "<input type='text' class='form-control' id='rating' name='rating' placeholder='3 Stars'>",
        "</div>",
        "<div class='form-group'>",
          "<input type='text' class='form-control' id='release' name='release' placeholder='May 20, 2015'>",
        "</div>",
        "<div class='form-group'>",
          "<input type='text' class='form-control' id='plot' name='plot' placeholder='This is a fictional ...'>",
        "</div>",
          "<button type='submit' id='postButton' class='btn btn-primary post'>Post</button>",
    "</form>"
  ].join(""),
  header: [
    "<nav class='navbar navbar-default navbar-fixed-top header'>",
      "<div class='container'>",
        "<h1>MooVee Mayhem</h1>",
        "<h4>[Read movie reviews or post your own]</h4>",
      "</div>",
    "</nav>"
  ].join(""),
  footer: [
    "<nav class='navbar navbar-inverse navbar-fixed-bottom footer'>",
      "<div class='container-fluid'>",
        "<div class='navbar-footer'>",
          "<a class='navbar-brand' href='#''>&copy 2015 MooVee Mahem</a>",
        "</div>",
        "<div>",
          "<ul class='nav navbar-nav' style='float: right'>",
            "<li class='active'><a href='#''>Home</a></li>",
            "<li><a href='#'>Contact</a></li>",
            "<li><a href='#'>About</a></li>",
          "</ul>",
        "</div>",
      "</div>",
    "</nav>"
    ].join(""),
};
